### ISSUE TITLE
每个方法都用到了，为什么不提出来？

### ISSUE THREAD

**Issue by iamxvbaba** [winlion/restgo-admin#1]
https://github.com/winlion/restgo-admin/blob/b93bcf0d9837f957231f2e3578532d779a40de88/service/UserService.go#L108

为什么将这个变量提出来，提升为一个.go文件全局变量的时候为nil

**Comment by winlion** [comment]
在restgo/OrmEngin.go 中我们定义了变量mapxormengin 
 var mapxormengin map[string]*xorm.Engine =make( map[string]*xorm.Engine)
在main.go中通过如下
for k, ds := range cfg.Datasource {
                //....
		restgo.SetEngin(k, e)
	}
SetEngin本质上是对mapxormengin进行添加新元素
  restgo.OrmEngin() 其实就是
 restgo.OrmEngin(“default”)
本质上是获取xorm.Engine
